config/routes.rb
Nicher::Application.routes.draw do
  resources :file_storages

  resources :folders

  resources :assets

  devise_for :users

  
  Nicher::Application.routes.draw do  
      
  resources :file_storages

  resources :folders

  resources :assets

  devise_for :users

    root :to => "home#index"  
  end
  
  match "assets/get/:id" => "assets#get", :as => "download"
  
  match "browse/:folder_id" => "home#browse", :as => "browse"  
  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"
  
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"
  
  match "assets/edit/:id" => "assets#edit", :as => "edit_file"
  
  
end

app/models/file_storage.rb
class FileStorage < ActiveRecord::Base
  attr_accessible :file_storage_id
  
  belongs_to :assets
end

app/controllers/file_storages_controller.rb
class FileStoragesController < ApplicationController
  
  before_filter :authenticate_user!  #authenticate for users before any methods is called  
  
  def index
    @file_storages = FileStorage.all
  end

  def show
    @file_storage = FileStorage.find(params[:id])
  end

  def new
    @file_storage = FileStorage.new
  end

  def create
    @file_storage = FileStorage.new(params[:file_storage])
    if @file_storage.save
      redirect_to @file_storage, :notice => "Successfully created file storage."
    else
      render :action => 'new'
    end
  end

  def edit
    @file_storage = FileStorage.find(params[:id])
  end

  def update
    @file_storage = FileStorage.find(params[:id])
    if @file_storage.update_attributes(params[:file_storage])
      redirect_to @file_storage, :notice  => "Successfully updated file storage."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @file_storage = FileStorage.find(params[:id])
    @file_storage.destroy
    redirect_to file_storages_url, :notice => "Successfully destroyed file storage."
  end
end

app/helpers/file_storages_helper.rb
module FileStoragesHelper
end

app/views/file_storages/_form.html.erb
<%= form_for @file_storage do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :file_storage_id %><br />
    <%= f.number_field :file_storage_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/file_storages/edit.html.erb
<% title "Edit File Storage" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @file_storage %> |
  <%= link_to "View All", file_storages_path %>
</p>

app/views/file_storages/index.html.erb
<% title "File Storages" %>

<table>
  <tr>
    <th>File Storage</th>
  </tr>
  <% for file_storage in @file_storages %>
    <tr>
      <td><%= file_storage.file_storage_id %></td>
      <td><%= link_to "Show", file_storage %></td>
      <td><%= link_to "Edit", edit_file_storage_path(file_storage) %></td>
      <td><%= link_to "Destroy", file_storage, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New File Storage", new_file_storage_path %></p>

app/views/file_storages/new.html.erb
<% title "New File Storage" %>

<%= render 'form' %>

<p><%= link_to "Back to List", file_storages_path %></p>

app/views/file_storages/show.html.erb
<% title "File Storage" %>

<p>
  <strong>File Storage:</strong>
  <%= @file_storage.file_storage_id %>
</p>

<p>
  <%= link_to "Edit", edit_file_storage_path(@file_storage) %> |
  <%= link_to "Destroy", @file_storage, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", file_storages_path %>
</p>