config/routes.rb
Nicher::Application.routes.draw do
  resources :file_storages

  resources :folders

  resources :assets

  devise_for :users

  
  Nicher::Application.routes.draw do  
      
  resources :file_storages

  resources :folders

  resources :assets

  devise_for :users

    root :to => "home#index"  
  end
  
  match "assets/get/:id" => "assets#get", :as => "download"
  
  match "browse/:folder_id" => "home#browse", :as => "browse"  
  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"
  
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"
  
  match "assets/edit/:id" => "assets#edit", :as => "edit_file"
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
    
  def index  
     if user_signed_in?  

       #show only root folders (which have no parent folders)  
       @folders = current_user.folders.roots   

       #show only root files which has no "folder_id", and limit the view to master version files
       @assets = current_user.assets.where("folder_id is NULL AND is_master_version = 1").order("uploaded_file_file_name desc")
       
       @url_prior_to_edit = request.fullpath
       session[:url_prior_to_edit] = @url_prior_to_edit
            
      end
  end  
  
  #this action is for viewing folders  
  def browse 
      if user_signed_in?  
     
        #get the folders owned/created by the current_user  
        @current_folder = current_user.folders.find(params[:folder_id])    
    
        if @current_folder  
      
          #getting the folders which are inside this @current_folder  
          @folders = @current_folder.children  
    
          #show only files under this current folder, and limit the view to master version files
          @assets = @current_folder.assets.where("is_master_version = 1").order("uploaded_file_file_name desc")

          render :action => "index"  
        else  
          flash[:error] = "Access is only allowed to your own folders."  
          redirect_to root_url  
        end  
        
        @url_prior_to_edit = request.fullpath
        session[:url_prior_to_edit] = @url_prior_to_edit
        
      end
  end
  
end

app/views/home/_breadcrumbs.html.erb
<div class="breadcrumbs">          
    <% if @current_folder #checking if we are under any folder %>  
        <%= link_to "Home", root_url %>  
        <% @current_folder.ancestors.reverse.each do |folder| %>  
            » <%= link_to folder.name, browse_path(folder) %>  
        <% end %>  
         »  <%= @current_folder.name %>  
    <% else #if we are not under any folder%>  
        Home  
    <% end %>  
</div>

app/views/home/_search.html.erb
<div class="asset_search">

	<%= form_tag assets_path, :method => :get  do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
		
	</p>
	<% end %>

</div>

app/views/home/index.html.erb
<% unless user_signed_in? %>  
   <h1>Welcome to Nicher</h1>  
   <p>A small document manager.</p>  
     
<% else %>  
   <div id="menu">  
   		<ul id= "top_menu">      
          <% if @current_folder %>  
		       <li><%= link_to "Upload", new_sub_file_path(@current_folder) %></li>  
		       <li><%= link_to "New Folder", new_sub_folder_path(@current_folder) %></li>
		  	   <li class="delete"><%= link_to "Delete", @current_folder, :confirm => 'Are you sure to delete this folder and all of its contents?', :method => :delete %></li>
		   <% else %>  
		       <li><%= link_to "Upload", new_asset_path %></li>  
		       <li><%= link_to "New Folder", new_folder_path %></li>  
		   <% end %>
   		</ul>  
   </div>
   <%= render :partial => "breadcrumbs" %>  

   <%= render :partial => "search" %>


   <div class="asset_list_header">  
       <div class="file_name_header">File Name</div>  
       <div class="file_size_header">Size</div>  
       <div class="file_last_updated_header">Modified</div>  
   </div>  
   <div class="asset_list">  
	   <!-- Listing Folders -->
       <% if @folders != nil
          @folders.each do |folder| %>  
	      <div class="asset_details folder">  
		        <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>  
		        <div class="file_size">-</div>  
		        <div class="file_last_updated">-</div>  
		        <div class="actions">  
		            <div class="rename">  
		                <%= link_to "Rename", rename_folder_path(folder) %>
		            </div>  
		            <div class="delete">  
		                   <%= link_to "Delete", folder, :confirm => 'Are you sure you want to delete the folder and all of its contents?', :method => :delete %>  
		            </div>  
		        </div>  
		    </div>
	 
	   <% end 
     end
	  %>	

	   <!-- Listing Files -->
       <% if @assets != nil
		  @assets.each do |asset| %>  
           <div class="asset_details file">  
		       <div class="file_name"><%= link_to asset.file_name, download_url(asset) %></div>  
		       <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>  
		       <div class="file_last_updated"><%= asset.updated_at %></div>  
		       <div class="actions">  
					<div class="edit">  
			              <%= link_to "Edit", edit_asset_path(asset) %>  
			           </div>
		           <div class="download">  
		              <%= link_to "Download", download_url(asset) %>  
		           </div>  
		           <div class="delete">  
		               <%= link_to "Delete", asset, :confirm => 'Are you sure?', :method => :delete %>   
		           </div>  
		       </div>  
		   </div>
       <% end
	    end
 		%>  

   </div>  
<% end %> 